### ISSUE TITLE
Update the repo with LAPACK 3.11.0 

### ISSUE THREAD

**Issue by ViralBShah** [Reference-LAPACK/lapack-release#7]
It would be nice to update this repo with the 3.11.0 release of LAPACK. Thank you.

**Comment by langou** [comment]
Thanks @ViralBShah. I had forgotten about this repo. We have been using GitHub tags for the releases. My preference would be to delete this repository and use GitHub tags for releases. Of course, we can do both (this repo and GitHub tags on the main repo). But I'd rather only do the GitHub tag. Are there some opinions? Comments? Suggestions? Best practices? Opinions welcome. If we keep the repo, I agree that we need to keep it updated (and not forget about it!). In any case, thanks for reminding us of the existence of this repo. I personally had forgotten about it. Julien.

**Comment by ViralBShah** [comment]
I thought this is the official repo since it is linked from the lapack release notes. We like to pull the official sources in Julia, and I was using this one.

I think the best thing would be to have an official repo and use Github's releases feature (with tags) to make releases. We can then pick up new releases from there. You can also tag all the old releases in there pretty quickly. 

I did find the branch for every release thing a bit odd and non standard.

**Comment by ViralBShah** [comment]
I now see the the lapack repo. I suggest just archiving this one. In any case the other one does everything just fine.
